title: Sri Guhan
logo: IMG_5769 (2)-modified.png
description: I'm Sri Guhan, a computer science student at the University of Exeter with a strong interest in data science and machine learning. I am fascinated by the potential to extract meaningful insights from vast, complex datasets and to develop predictive models that solve real-world problems. My goal is to combine my passion for data analysis with machine learning techniques to create impactful, data-driven solutions that push the boundaries of technology.
show_downloads: true
theme: jekyll-theme-minimal
